name: MICA
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - biopython=1.78
  - numpy=1.19.1
  - pandas=1.1.3
  - pip=21.2.1
  - python=3.8.12
  - pytorch=1.8.1
  - scipy=1.5.2
  - pip:
    - argparse==1.4.0
    - atom3d==0.2.4
    - mrcfile==1.3.0
    - superpose3d==1.1.1
    - tqdm==4.61.2
    - scikit-image==0.18.2
    - networkx==2.6.3
    - einops
    - rotary-embedding-torch
    - natsort
    - wandb
    - open3d==0.13.0


