#!/bin/bash

# MICA Atomic Model Building Pipeline
# Executes 3 programs in order and logs execution times

set -e  # Exit on any error

# Script version and info
SCRIPT_NAME="MICA_pipeline.sh"
VERSION="1.2"

# Default values
VERBOSE=false
LOG_FILE=""
DEVICE="cuda"  # Default device

# Function to display help
show_help() {
    cat << EOF
$SCRIPT_NAME v$VERSION - MICA Atomic Model Building Pipeline

DESCRIPTION:
    This script executes three protein processing programs in sequence:
    1. process_AF3_results.py - Process AlphaFold 3 results
    2. dock_in_map.py - Dock structures in cryo-EM maps
    3. run.py - Run data preprocessing, deep learning prediction and atomic model building

USAGE:
    $SCRIPT_NAME [OPTIONS]
    $SCRIPT_NAME -f <fasta_file> -a <af3_results> -m <map_file> [OPTIONS]

OPTIONS:
    -f, --fasta_path PATH          Path to FASTA file (required)
    -a, --AF3_results_path DIR     Path to AF3 results directory (required)
    -m, --map_path PATH            Path to cryo-EM map file (required)
    -c, --contour_level VALUE      Contour level for docking (required)
    -r, --resolution VALUE         Resolution value (required)
    -p, --pulchra_path PATH        Path to Pulchra executable (required)
    -x, --phenix_act PATH          Path to Phenix activation script (required)
    -d, --device DEVICE            Device for computation (default: cuda)
                                   Options: 'cpu', 'cuda', 'cuda:1', etc.
    -h, --help                     Show this help message
    
EXAMPLES:
    # Interactive mode (prompts for all inputs)
    ./$SCRIPT_NAME

    # Example Usage with default device (cuda)
    ./$SCRIPT_NAME \\
        -f input/15635/8at6.fasta \\
        -a input/15635/AF3_results \\
        -m input/15635/emd_15635.map \\
        -c 0.0242 \\
        -r 3.7 \\
        -p modules/pulchra304/src/pulchra \\
        -x <your/path/to/phenix/phenix_env.sh>

    # Example Usage with specific device
    ./$SCRIPT_NAME \\
        -f input/15635/8at6.fasta \\
        -a input/15635/AF3_results \\
        -m input/15635/emd_15635.map \\
        -c 0.0242 \\
        -r 3.7 \\
        -p modules/pulchra304/src/pulchra \\
        -x <your/path/to/phenix/phenix_env.sh> \\
        -d cuda:1

OUTPUT:
    Creates multiple output files:
    1. CSV timing log:
       - Format: {fasta_name}_execution_times_YYYYMMDD_HHMMSS.csv
       - Example: 8at6_execution_times_20240826_143022.csv
    
    2. Final atomic model (generated by pipeline):
       - Format: output/{AF3_results_dirname}_{fasta_name}_MICA_all_atom_model.pdb
       - Example: output/AF3_results_8at6_MICA_all_atom_model.pdb

REQUIREMENTS:
    - Python environment with required packages
    - Phenix installation
    - CUDA (if using GPU device)

AUTHOR:
    Rajan Gyawali | MICA for protein structure prediction

EOF
}

# Function to log messages with timestamp
log_message() {
    local message="$1"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "$timestamp - INFO - $message"
}

# Function to calculate time difference in minutes (with 2 decimal places)
time_diff() {
    local seconds=$((end_time - start_time))
    echo "scale=2; $seconds / 60" | bc -l
}

# Function to validate file exists
validate_file() {
    local file="$1"
    local description="$2"
    if [ ! -f "$file" ]; then
        echo "Error: $description file not found: $file" >&2
        exit 1
    fi
}

# Function to validate directory exists
validate_dir() {
    local dir="$1"
    local description="$2"
    if [ ! -d "$dir" ]; then
        echo "Error: $description directory not found: $dir" >&2
        exit 1
    fi
}

# Function to validate device option
validate_device() {
    local device="$1"
    if [[ ! "$device" =~ ^(cpu|cuda|cuda:[0-9]+)$ ]]; then
        echo "Error: Invalid device '$device'. Valid options: 'cpu', 'cuda', 'cuda:N' (where N is a number)" >&2
        exit 1
    fi
}

# Function to prompt for missing required parameters
prompt_for_missing() {
    if [ -z "$fasta_path" ]; then
        read -p "Path to FASTA file: " fasta_path
    fi
    
    if [ -z "$AF3_results_path" ]; then
        read -p "Path to AF3 results: " AF3_results_path
    fi
    
    if [ -z "$map_path" ]; then
        read -p "Path to cryo-EM map: " map_path
    fi
    
    if [ -z "$contour_level" ]; then
        read -p "Contour level: " contour_level
    fi
    
    if [ -z "$resolution" ]; then
        read -p "Resolution: " resolution
    fi
    
    if [ -z "$pulchra_path" ]; then
        read -p "Path to Pulchra: " pulchra_path
    fi
    
    if [ -z "$phenix_act" ]; then
        read -p "Path to Phenix activation: " phenix_act
    fi
}

# Parse command line arguments
fasta_path=""
AF3_results_path=""
map_path=""
contour_level=""
resolution=""
pulchra_path=""
phenix_act=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--fasta)
            fasta_path="$2"
            shift 2
            ;;
        -a|--af3)
            AF3_results_path="$2"
            shift 2
            ;;
        -m|--map)
            map_path="$2"
            shift 2
            ;;
        -c|--contour)
            contour_level="$2"
            shift 2
            ;;
        -r|--resolution)
            resolution="$2"
            shift 2
            ;;
        -p|--pulchra)
            pulchra_path="$2"
            shift 2
            ;;
        -x|--phenix)
            phenix_act="$2"
            shift 2
            ;;
        -d|--device)
            DEVICE="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo "Error: Unknown option $1" >&2
            echo "Use -h or --help for usage information" >&2
            exit 1
            ;;
    esac
done

# Show header
printf '%.0s=' {1..80}; echo
echo "🧬 SEQUENTIAL PROTEIN PROCESSING PIPELINE v$VERSION"
printf '%.0s=' {1..80}; echo
echo "This script will execute 3 programs in sequence:"
echo "1. process_AF3_results.py"
echo "2. dock_in_map.py" 
echo "3. run.py"
echo ""

# Prompt for any missing required parameters
prompt_for_missing

# Validate device option
validate_device "$DEVICE"

# Validate all required parameters are provided
if [ -z "$fasta_path" ] || [ -z "$AF3_results_path" ] || [ -z "$map_path" ] || \
   [ -z "$contour_level" ] || [ -z "$resolution" ] || \
   [ -z "$pulchra_path" ] || [ -z "$phenix_act" ]; then
    echo "Error: Missing required parameters" >&2
    echo "Use -h or --help for usage information" >&2
    exit 1
fi

# Validate files and directories exist
validate_file "$fasta_path" "FASTA"
validate_dir "$AF3_results_path" "AF3 results"
validate_file "$map_path" "Cryo-EM map"
validate_file "$phenix_act" "Phenix activation"

# Set up CSV log file
FASTA_BASENAME=$(basename "$fasta_path")
FASTA_NAME="${FASTA_BASENAME%.*}"
LOG_FILE="${FASTA_NAME}_execution_times_$(date +%Y%m%d_%H%M%S).csv"

# Create CSV log file with headers
echo "Step,Start Time,End Time,Duration (minutes),Status" > "$LOG_FILE"

echo ""
printf '%.0s=' {1..80}; echo
echo "📊 CONFIGURATION SUMMARY"
printf '%.0s=' {1..80}; echo
echo "FASTA file: $fasta_path"
echo "AF3 results: $AF3_results_path"
echo "Cryo-EM map: $map_path"
echo "Contour level: $contour_level"
echo "Resolution: $resolution"
echo "Pulchra path: $pulchra_path"
echo "Phenix activation: $phenix_act"
echo "Device: $DEVICE"
echo "CSV log file: $LOG_FILE"
echo ""

# Initialize total time tracking
TOTAL_START=$(date +%s)

echo ""
printf '%.0s=' {1..80}; echo
echo "🚀 STARTING PIPELINE EXECUTION"
printf '%.0s=' {1..80}; echo
log_message "Pipeline started"

# Step 1: process_AF3_results.py
echo ""
log_message "Step 1: Running process_AF3_results.py"
start_time=$(date +%s)
start_timestamp=$(date '+%Y-%m-%d %H:%M:%S')

STEP1_CMD="python utils/process_AF3_results.py -f \"$fasta_path\" -a \"$AF3_results_path\" -d \"$DEVICE\""
log_message "Executing: $STEP1_CMD"

if python utils/process_AF3_results.py -f "$fasta_path" -a "$AF3_results_path"; then
    end_time=$(date +%s)
    end_timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    duration=$(time_diff)
    status="SUCCESS"
    log_message "Step 1 completed successfully in ${duration} minutes"
else
    end_time=$(date +%s)
    end_timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    duration=$(time_diff)
    status="FAILED"
    log_message "Step 1 FAILED after ${duration} minutes"
    echo "Step 1,${start_timestamp},${end_timestamp},${duration},${status}" >> "$LOG_FILE"
    exit 1
fi

echo "Step 1,${start_timestamp},${end_timestamp},${duration},${status}" >> "$LOG_FILE"

# Step 2: dock_in_map.py
echo ""
log_message "Step 2: Running dock_in_map.py"
start_time=$(date +%s)
start_timestamp=$(date '+%Y-%m-%d %H:%M:%S')

STEP2_CMD="python utils/dock_in_map.py -m \"$map_path\" -c \"$contour_level\" -r \"$resolution\" -f \"$fasta_path\" -a \"$AF3_results_path\" --phenix_act \"$phenix_act\""
log_message "Executing: $STEP2_CMD"

if python utils/dock_in_map.py \
    -m "$map_path" \
    -c "$contour_level" \
    -r "$resolution" \
    -f "$fasta_path" \
    -a "$AF3_results_path" \
    --phenix_act "$phenix_act"; then
    end_time=$(date +%s)
    end_timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    duration=$(time_diff)
    status="SUCCESS"
    log_message "Step 2 completed successfully in ${duration} minutes"
else
    end_time=$(date +%s)
    end_timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    duration=$(time_diff)
    status="FAILED"
    log_message "Step 2 FAILED after ${duration} minutes"
    echo "Step 2,${start_timestamp},${end_timestamp},${duration},${status}" >> "$LOG_FILE"
    exit 1
fi

echo "Step 2,${start_timestamp},${end_timestamp},${duration},${status}" >> "$LOG_FILE"

# Step 3: run.py
echo ""
log_message "Step 3: Running run.py"
start_time=$(date +%s)
start_timestamp=$(date '+%Y-%m-%d %H:%M:%S')

STEP3_CMD="python run.py -m \"$map_path\" -f \"$fasta_path\" -a \"$AF3_results_path\" --run_pulchra --pulchra_path=\"$pulchra_path\" --run_phenix --phenix_act=\"$phenix_act\" --resolution=\"$resolution\" --device=\"$DEVICE\""
log_message "Executing: $STEP3_CMD"

if python run.py \
    -m "$map_path" \
    -f "$fasta_path" \
    -a "$AF3_results_path" \
    --run_pulchra \
    --pulchra_path="$pulchra_path" \
    --run_phenix \
    --phenix_act="$phenix_act" \
    --resolution="$resolution" \
    --device="$DEVICE"; then
    end_time=$(date +%s)
    end_timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    duration=$(time_diff)
    status="SUCCESS"
    log_message "Step 3 completed successfully in ${duration} minutes"
else
    end_time=$(date +%s)
    end_timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    duration=$(time_diff)
    status="FAILED"
    log_message "Step 3 FAILED after ${duration} minutes"
    echo "Step 3,${start_timestamp},${end_timestamp},${duration},${status}" >> "$LOG_FILE"
    exit 1
fi

echo "Step 3,${start_timestamp},${end_timestamp},${duration},${status}" >> "$LOG_FILE"

# Calculate total execution time
TOTAL_END=$(date +%s)
TOTAL_DURATION_SECONDS=$((TOTAL_END - TOTAL_START))
TOTAL_DURATION=$(echo "scale=2; $TOTAL_DURATION_SECONDS / 60" | bc -l)
total_start_timestamp=$(date -d @$TOTAL_START '+%Y-%m-%d %H:%M:%S')
total_end_timestamp=$(date -d @$TOTAL_END '+%Y-%m-%d %H:%M:%S')

echo "Total Pipeline,${total_start_timestamp},${total_end_timestamp},${TOTAL_DURATION},SUCCESS" >> "$LOG_FILE"

echo ""
printf '%.0s=' {1..80}; echo
echo "✅ PIPELINE EXECUTION COMPLETE"
printf '%.0s=' {1..80}; echo
log_message "All steps completed successfully!"
log_message "Total execution time: ${TOTAL_DURATION} minutes"
log_message "Execution times logged to: $LOG_FILE"

echo ""
echo "Summary:"
echo "- All 3 steps executed successfully"
echo "- Total time: ${TOTAL_DURATION} minutes"
echo "- Device used: $DEVICE"
echo "- Log file: $LOG_FILE"

echo ""
printf '%.0s=' {1..80}; echo
echo "📄 EXECUTION LOG"
printf '%.0s=' {1..80}; echo
cat "$LOG_FILE"